# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='modify_time',
            field=models.DateField(blank=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modify_time',
            field=models.DateField(blank=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
