# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170317_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Node', verbose_name='\u8282\u70b9'),
        ),
    ]
