# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170323_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='image/%Y/%m', verbose_name='\u8282\u70b9\u56fe\u7247'),
        ),
    ]
