# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_node_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='\u63cf\u8ff0'),
        ),
    ]
