# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_node_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u8282\u70b9\u540d\u79f0'),
        ),
    ]
