# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170325_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.CharField(max_length=50, null=True, verbose_name='\u4e2a\u4eba\u7f51\u7ad9'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], max_length=10, verbose_name='\u6027\u522b'),
        ),
    ]
