# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170326_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('\u7528\u6237\u6ce8\u518c', 'register'), ('\u5fd8\u8bb0\u5bc6\u7801', 'forgot_pwd'), ('\u66f4\u6539\u6ce8\u518c\u90ae\u7bb1', 'update_email')], max_length=50, verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default/avatar.png', max_length=200, upload_to='image/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
